// The block below is generated from the runtime schemas in helix-commerce-api
// (src/schemas/*) and pushed here by its `codegen:sync` workflow. Do not edit it
// by hand and do not add hand-written types between the markers -- they are the
// single source of truth for these public types and the region is overwritten on
// every sync. The first sync populates this region; until then it is intentionally
// empty.
// >>> BEGIN generated by helix-commerce-api -- DO NOT EDIT
/**
 * schema.org availability status for a product or offer.
 */
export type SchemaOrgAvailability = "BackOrder" | "Discontinued" | "InStock" | "InStoreOnly" | "LimitedAvailability" | "MadeToOrder" | "OnlineOnly" | "OutOfStock" | "PreOrder" | "PreSale" | "Reserved" | "SoldOut";

/**
 * schema.org item condition.
 */
export type SchemaOrgItemCondition = "DamagedCondition" | "NewCondition" | "RefurbishedCondition" | "UsedCondition";

/**
 * Unit of weight measurement.
 */
export type WeightUnit = "kg" | "g" | "lb" | "oz";

/**
 * Unit of dimension measurement.
 */
export type DimensionsUnit = "cm" | "mm" | "in";

/**
 * Aggregate customer rating for schema.org structured data.
 */
export interface SchemaOrgAggregateRating {
  /** Average rating value. Numeric string; converted to a number in JSON-LD. */
  ratingValue?: string;
  /** Total number of ratings. Numeric string; converted to an integer in JSON-LD. */
  reviewCount?: string;
  /** Best possible rating. Numeric string. */
  bestRating?: string;
  /** Worst possible rating. Numeric string. */
  worstRating?: string;
}

/**
 * Price information for a product or variant.
 */
export interface ProductBusPrice {
  /** Final price the customer pays, as a decimal string (e.g. "19.99"). */
  final?: string;
  /** ISO 4217 currency code, e.g. "USD". */
  currency?: string;
  /** Original price before any discount, as a decimal string. */
  regular?: string;
}

/**
 * Product weight for display and JSON-LD structured data.
 */
export interface ProductBusWeight {
  /** Numeric weight value. */
  value: number;
  /** Unit of weight measurement. */
  unit: WeightUnit;
}

/**
 * Physical dimensions used for shipping rate calculation.
 */
export interface ShippingDimensions {
  /** Product weight for display and JSON-LD structured data. */
  weight?: ProductBusWeight;
  /** Height in the declared dimensionsUnit. */
  height?: number;
  /** Width in the declared dimensionsUnit. */
  width?: number;
  /** Depth in the declared dimensionsUnit. */
  depth?: number;
  /** Unit of dimension measurement. */
  dimensionsUnit?: DimensionsUnit;
}

/**
 * Product image asset.
 */
export interface ProductBusImage {
  /** Absolute URL of the image. */
  url: string;
  /** Accessible alt text for the image. */
  label?: string;
  /** Original filename of the image. */
  filename?: string;
  /** Semantic roles assigned to this image, e.g. "thumbnail". */
  roles?: string[];
}

/**
 * A single selectable value for a product option.
 */
export interface ProductBusOptionValue {
  /** Unique identifier for this option value. */
  id?: string;
  /** Display label for this option value (e.g. "Red", "Large"). */
  value: string;
  /** Internal UID used by some backends. */
  uid?: string;
}

/**
 * A configurable product option with its available values (e.g. Color, Size).
 */
export interface ProductBusOption {
  /** Option identifier, typically matching the attribute code. */
  id?: string;
  /** Display label for the option group (e.g. "Color"). */
  label: string;
  /** Sort order for display. */
  position?: number;
  /** Available values for this option. */
  values: ProductBusOptionValue[];
}

/**
 * Price for a bundle component. Narrower than ProductBusPrice -- no currency field (currency comes from the parent line item).
 */
export interface BundleItemPrice {
  /** Component price as a decimal string. */
  final: string;
  /** Pre-discount price for display purposes. */
  regular?: string;
}

/**
 * Option pair on a configurable bundle item variant. The server resolves which variant to ship by matching every entry here against the parent line item's selectedOptions.
 */
export interface BundleItemVariantOption {
  /** Option identifier, matched against selectedOptions[].id. */
  id: string;
  /** Option value label, matched against selectedOptions[].value. */
  name: string;
}

/**
 * One variant of a configurable bundle item. The server selects the variant whose options are all satisfied by the parent line item's selectedOptions.
 */
export interface BundleItemVariant {
  /** SKU for this variant. */
  sku: string;
  /** Display name for this variant. */
  name?: string;
  /** Price for a bundle component. Narrower than ProductBusPrice -- no currency field (currency comes from the parent line item). */
  price: BundleItemPrice;
  /** Option pairs that identify this variant. */
  options: BundleItemVariantOption[];
  /** Per-variant tax classification code. Falls back to the bundle parent's taxCode when absent. */
  taxCode?: string;
  /** Supplementary tax data. Falls back to the bundle parent's taxData when absent. */
  taxData?: Record<string, unknown>;
}

/**
 * One entry in a bundle product's composition. May be a simple item (sku + price) or a configurable item (variants array). Presence of the parent product's bundleItems array marks it as a bundle.
 */
export interface BundleItem {
  /** SKU for a simple bundle item. */
  sku?: string;
  /** Display name for a simple bundle item. */
  name?: string;
  /** Price for a bundle component. Narrower than ProductBusPrice -- no currency field (currency comes from the parent line item). */
  price?: BundleItemPrice;
  /** Variants for a configurable bundle item. When present, the server selects one variant at preview time. */
  variants?: BundleItemVariant[];
  /** Per-component tax classification code. Falls back to the bundle parent's taxCode when absent. */
  taxCode?: string;
  /** Supplementary tax data. Falls back to the bundle parent's taxData when absent. */
  taxData?: Record<string, unknown>;
}

/**
 * A single shipping option in Google Merchant Center format.
 */
export interface MerchantFeedShipping {
  /** Two-letter country code (ISO 3166-1 alpha-2). */
  country?: string;
  /** State or region code. */
  region?: string;
  /** Shipping service label (e.g. "Standard", "Overnight"). */
  service?: string;
  /** Shipping cost with currency code (e.g. "16.00 USD"). */
  price?: string;
  /** Minimum order handling time in business days. */
  min_handling_time?: string;
  /** Maximum order handling time in business days. */
  max_handling_time?: string;
  /** Minimum shipping transit time in business days. */
  min_transit_time?: string;
  /** Maximum shipping transit time in business days. */
  max_transit_time?: string;
}

/**
 * A purchasable variant of a configurable product.
 */
export interface ProductBusVariant {
  /** Unique stock-keeping unit identifier. */
  sku: string;
  /** Display name for this variant. */
  name: string;
  /** Price information for a product or variant. */
  price?: ProductBusPrice;
  /** Canonical URL for this variant. */
  url: string;
  /** Images for this variant. */
  images: ProductBusImage[];
  /** Global Trade Item Number (barcode). */
  gtin?: string;
  /** Variant-specific description. */
  description?: string;
  /** schema.org availability status for a product or offer. */
  availability?: SchemaOrgAvailability;
  /** Option values that identify this variant (e.g. color=Red, size=Large). */
  options?: ProductBusOptionValue[];
  /** schema.org item condition. */
  itemCondition?: SchemaOrgItemCondition;
  custom?: Record<string, unknown>;
  /** Additional schema.org properties shallow-merged into this variant's Offer in the auto-generated JSON-LD. Max 16,000 characters when serialized. */
  jsonldExtensions?: Record<string, unknown>;
  /** Product weight for display and JSON-LD structured data. */
  weight?: ProductBusWeight;
  /** Physical dimensions used for shipping rate calculation. */
  shippingDimensions?: ShippingDimensions;
}

/**
 * A Product Bus catalog entry representing a single product or configurable product.
 */
export interface ProductBusEntry {
  /** Unique stock-keeping unit identifier. */
  sku: string;
  /** URL path for this product (e.g. "/products/my-product"). */
  path: string;
  /** URL key used to construct the canonical path. */
  urlKey?: string;
  /** Full product description. */
  description?: string;
  /** Display name for the product. */
  name: string;
  /** HTML meta title override. */
  metaTitle?: string;
  /** HTML meta description override. */
  metaDescription?: string;
  /** Global Trade Item Number (barcode). */
  gtin?: string;
  /** Canonical absolute URL for the product. */
  url?: string;
  /** Brand or manufacturer name. */
  brand?: string;
  /** Product type identifier (e.g. "simple", "configurable", "bundle"). */
  type?: string;
  /** schema.org availability status for a product or offer. */
  availability?: SchemaOrgAvailability;
  /** ISO 8601 date when the product becomes available. */
  availabilityDate?: string;
  /** Price information for a product or variant. */
  price?: ProductBusPrice;
  /** schema.org item condition. */
  itemCondition?: SchemaOrgItemCondition;
  /** Arbitrary key/value metadata attached to the product. */
  metadata?: Record<string, string>;
  /** Configurable options available for this product (e.g. Color, Size). */
  options?: ProductBusOption[];
  /** Aggregate customer rating for schema.org structured data. */
  aggregateRating?: SchemaOrgAggregateRating;
  /** Freeform product specifications (HTML or plain text). */
  specifications?: string;
  /** Product images. */
  images?: ProductBusImage[];
  /** Available variants for a configurable product. */
  variants?: ProductBusVariant[];
  /** Full JSON-LD override. When present, replaces the auto-generated structured data. */
  jsonld?: string;
  custom?: Record<string, unknown>;
  /** Additional schema.org properties shallow-merged into the auto-generated Product JSON-LD object. Ignored when jsonld override is used. Max 32,000 characters when serialized. */
  jsonldExtensions?: Record<string, unknown>;
  shipping?: string | MerchantFeedShipping | MerchantFeedShipping[];
  /** Bundle composition. Presence of this array (regardless of contents) marks this product as a bundle. */
  bundleItems?: BundleItem[];
  feeds?: { common?: { geoTargetCountries?: string[]; geoStoreCountry?: string; }; oai?: { isEligibleForSearch: boolean; isEligibleForCheckout: boolean; }; };
  /** Product weight for display and JSON-LD structured data. */
  weight?: ProductBusWeight;
  /** Physical dimensions used for shipping rate calculation. */
  shippingDimensions?: ShippingDimensions;
  /** Tax classification code for this product. */
  taxCode?: string;
  /** Supplementary tax data passed to the tax provider. */
  taxData?: Record<string, unknown>;
  /** ISO 3166-1 alpha-2 store country code. */
  country?: string;
  /** BCP-47 locale tag for this product entry. */
  locale?: string;
}

/**
 * A shipping or billing address.
 */
export interface OrderAddress {
  /** Full name of the recipient. */
  name: string;
  /** Company name. */
  company?: string;
  /** Primary street address line. */
  address1: string;
  /** Secondary address line (apartment, suite, etc.). */
  address2?: string;
  /** City name. */
  city: string;
  /** State or province code. */
  state: string;
  /** Postal or ZIP code. */
  zip: string;
  /** ISO 3166-1 alpha-2 country code. */
  country: string;
  /** Phone number. */
  phone?: string;
  email: string;
  /** Whether this is the default address for the customer. */
  isDefault?: boolean;
  /** Whether this address has been validated by an address verification service. */
  isValidated?: boolean;
}

/**
 * Customer contact information provided at checkout.
 */
export interface OrderCustomer {
  /** Customer first name. */
  firstName: string;
  /** Customer last name. */
  lastName: string;
  email: string;
  /** Customer phone number. */
  phone?: string;
}

/**
 * A customer-selected option value for a line item (e.g. color=Red).
 */
export interface SelectedOption {
  /** Option identifier. */
  id: string;
  /** Selected value. */
  value: string;
}

/**
 * A resolved bundle component line item nested on a bundle parent order item.
 */
export interface NestedBundleItem {
  /** Display name of the component. */
  name?: string;
  /** SKU of the component. */
  sku?: string;
  /** Product page path of the component. */
  path: string;
  /** Quantity for this component. */
  quantity: number;
  /** Price information for a product or variant. */
  price: ProductBusPrice;
}

/**
 * A single line item in an order or estimate.
 */
export interface OrderItem {
  /** Display name for this line item. */
  name?: string;
  /** Optional customer note for this line item. */
  note?: string;
  /** SKU of the product. */
  sku: string;
  /** Product page path. */
  path: string;
  /** Product image URL for order confirmation display. */
  imageUrl?: string;
  /** Canonical product URL. */
  productUrl?: string;
  /** Quantity ordered. */
  quantity: number;
  /** Price information for a product or variant. */
  price: ProductBusPrice;
  /** Physical dimensions used for shipping rate calculation. */
  shippingDimensions?: ShippingDimensions;
  /** Option values selected by the customer. */
  selectedOptions?: SelectedOption[];
  /** Resolved bundle component line items nested on a bundle parent. Not counted toward the order subtotal -- the parent price is the chargeable value. */
  bundleItems?: NestedBundleItem[];
  /** Arbitrary custom data for this line item. */
  custom?: Record<string, unknown>;
}
// <<< END generated by helix-commerce-api

// Everything below this point is hand-maintained in helix-product-shared.

/**
 * Per-value meanings for {@link SchemaOrgAvailability}. Types-only doc carrier
 * (no runtime value) so documentation tooling can read each value's meaning.
 */
export type SchemaOrgAvailabilityValues = {
  /** Product is available for order but currently out of stock. */
  BackOrder: 'BackOrder';
  /** Product is no longer being manufactured or sold. */
  Discontinued: 'Discontinued';
  /** Product is available for immediate purchase. */
  InStock: 'InStock';
  /** Product is only available for purchase in physical stores. */
  InStoreOnly: 'InStoreOnly';
  /** Product has limited stock available. */
  LimitedAvailability: 'LimitedAvailability';
  /** Product is manufactured upon order placement. */
  MadeToOrder: 'MadeToOrder';
  /** Product is only available for online purchase. */
  OnlineOnly: 'OnlineOnly';
  /** Product is temporarily out of stock. */
  OutOfStock: 'OutOfStock';
  /** Product can be ordered before official release. */
  PreOrder: 'PreOrder';
  /** Product is available for pre-sale purchase. */
  PreSale: 'PreSale';
  /** Product is reserved and not available for general purchase. */
  Reserved: 'Reserved';
  /** Product has sold out completely. */
  SoldOut: 'SoldOut';
};

/**
 * Per-value meanings for {@link SchemaOrgItemCondition}. Types-only doc carrier
 * (no runtime value) so documentation tooling can read each value's meaning.
 */
export type SchemaOrgItemConditionValues = {
  /** Product has damage or defects. */
  DamagedCondition: 'DamagedCondition';
  /** Product is brand new and unused. */
  NewCondition: 'NewCondition';
  /** Product has been professionally restored to working condition. */
  RefurbishedCondition: 'RefurbishedCondition';
  /** Product has been previously used. */
  UsedCondition: 'UsedCondition';
};

/**
 * Simple bundle item -- a single SKU regardless of the parent's options.
 *
 * `taxCode` and `taxData` are optional per-component overrides of the bundle
 * parent's tax classification. When present, the Commerce API uses them for
 * the component's line in the tax-provider projection; when absent, the
 * projection falls back to the bundle parent's `taxCode` / `taxData`.
 */
export interface BundleItemSimple {
  sku: string;
  name: string;
  price: BundleItemPrice;
  taxCode?: string;
  taxData?: Record<string, unknown>;
}

/**
 * Configurable bundle item -- the server selects one variant at preview time
 * based on the parent's `selectedOptions`.
 */
export interface BundleItemConfigurable {
  variants: BundleItemVariant[];
}

/** Common feed settings shared across product distribution channels. */
export interface ProductBusFeedCommon {
  /** Target countries for product feeds. */
  geoTargetCountries?: string[];
  /** Store country for feed generation. */
  geoStoreCountry?: string;
}

/** Product feed eligibility for the OpenAI / agentic commerce feed. */
export interface ProductBusFeedOpenAI {
  /** Whether the product is eligible for search feeds. */
  isEligibleForSearch: boolean;
  /** Whether the product supports checkout via feeds. */
  isEligibleForCheckout: boolean;
}

/** Feed configuration for product distribution. */
export interface ProductBusFeeds {
  /** Common feed settings. */
  common?: ProductBusFeedCommon;
  /** OpenAI / agentic commerce feed eligibility. */
  oai?: ProductBusFeedOpenAI;
}

/** An order request body for placing or previewing an order. */
export interface Order {
  /** Customer contact details supplied with the order. */
  customer: OrderCustomer;
  /** Shipping address. */
  shipping: OrderAddress;
  /** Billing address for payment AVS verification. Falls back to shipping if omitted. */
  billing?: OrderAddress;
  /** Line items in the order. */
  items: OrderItem[];
  /** Customer language as a BCP-47 tag. */
  locale?: string;
  /** Store country as an ISO 3166-1 alpha-2 code. Falls back to shipping.country if absent. */
  country?: string;
  /** Shipping method selected by the customer from the estimate rates. Required for order preview. */
  shippingMethod?: { id: string };
  /** Estimate token from a prior order preview. Used to lock in estimates at order creation time. */
  estimateToken?: string;
  /** Payment method identifier. */
  paymentMethod?: string;
  /** Coupon code applied to the order. */
  couponCode?: string;
  /** Origin of the coupon code, e.g. a campaign source (order preview only). */
  couponSource?: string;
  /** Optional gift message to include with the order. Max 250 characters. */
  giftMessage?: string;
  /** IANA timezone captured from the shopper's browser at checkout. */
  customerTimezone?: string;
  /** Customer-defined key/value pairs for linking the order to external systems. */
  custom?: Record<string, string>;
}

// ─── Error types ─────────────────────────────────────────────────────────────

/** A single field-level validation failure. */
export interface ValidationErrorDetail {
  /** JSON path to the offending value, e.g. `$.allowedOrigins[0]`. */
  path: string;
  /** What was wrong at this path. */
  message: string;
  /** Optional extra context. */
  details?: string;
}

/** Standard error envelope returned for non-2xx responses. */
export interface ErrorResponse {
  /** Machine-readable error code (also sent as the `x-error-code` header). */
  code: string;
  /** Human-readable error message (also sent as the `x-error` header). */
  message: string;
  /** The resource type involved, when applicable. */
  resource?: string;
  /** Whether the caller may retry the request. */
  retryable?: boolean;
  /** Optional structured detail. */
  details?: Record<string, unknown>;
}

/** Error envelope returned when the request body fails schema validation (HTTP 400). */
export interface ValidationErrorResponse {
  /** Machine-readable error code. */
  code: string;
  /** Human-readable error message. */
  message: string;
  /** Per-field validation failures. */
  errors?: ValidationErrorDetail[];
}

// ─── Estimate types ───────────────────────────────────────────────────────────

export interface TaxRate {
  country: string;
  state: string;
  /** Tax rate as a percentage, e.g. 12.0 for 12% */
  rate: number;
  id?: string;
}

export interface ShippingRate {
  /** Unique identifier from the shipping configuration sheet */
  id: string;
  /** Customer-facing label, e.g. "Standard Shipping: 8-10 Business Days" */
  label: string;
  /** Shipping method type, e.g. "standard" */
  type: string;
  /** Shipping cost as a decimal value */
  rate: number;
}

export interface OrderPreview {
  /** Order subtotal as a decimal string, e.g. "99.95" */
  subtotal: string;
  /** Calculated tax amount as a decimal string */
  taxAmount: string;
  /** Tax rate percentage used for the calculation, e.g. 12.0 for 12% */
  taxRate: number;
  /** The shipping method selected by the customer */
  shippingMethod: ShippingRate;
  /** Applied price/discount rules -- format not yet defined */
  discounts: unknown[];
  /** Total (subtotal + tax + shipping) as a decimal string */
  total: string;
  /** Short-lived signed JWT encapsulating estimate results for order submission */
  estimateToken: string;
}

// ─── Journal entry types ────────────────────────────────────────────────────

/** Common envelope shared by all journal entry types */
export interface JournalEntry {
  /** Unique entry identifier */
  id: string;
  /** ISO 8601 timestamp of the event */
  timestamp: string;
  /** Which journal this entry belongs to */
  journal: 'orders' | 'general';
  /** Event type (e.g. 'create', 'updateState', 'subrequest', 'update', 'add', 'remove') */
  event: string;
  /** Owning org */
  org: string;
  /** Owning site */
  site: string;
}

/** Base interface shared by all order journal entries */
export interface BaseOrderJournalEntry extends JournalEntry {
  journal: 'orders';
  /** The order this entry is for */
  orderId: string;
}

/** Emitted when an order is created or a merchant/system updates its state */
export interface OrderStateJournalEntry extends BaseOrderJournalEntry {
  event: 'create' | 'state_updated';
  /** New order state */
  state: string;
  /** Who triggered the event (e.g. "customer", "admin:ops@example.com") */
  actor: string;
  /** Human-readable reason for the state change */
  reason?: string;
}

/** Emitted for payment provider interactions (initiate, callback, cancel) */
export interface PaymentOrderJournalEntry extends BaseOrderJournalEntry {
  event: 'payment_initiated' | 'payment_completed' | 'payment_cancelled';
  /** Payment provider name (e.g. "chase") */
  provider: string;
  /** Payment attempt identifier */
  attemptId?: string;
  /** Idempotency key used for the payment request */
  idempotencyKey?: string;
  /** Payment method (e.g. "Visa", "Mastercard") */
  paymentMethod?: string;
  /** Outgoing request to the provider */
  request?: Record<string, unknown>;
  /** Provider response */
  response?: Record<string, unknown>;
  /** Time the provider call took in milliseconds */
  durationMs?: number;
}

/** Emitted when order custom data is updated via the custom API */
export interface OrderCustomUpdatedJournalEntry extends BaseOrderJournalEntry {
  event: 'custom_updated';
  /** The full custom data after the update */
  custom: Record<string, string>;
  /** Who triggered the event (e.g. "service-token:my-integration") */
  actor?: string;
}

/** Discriminated union of all order journal entry types */
export type OrderJournalEntry = OrderStateJournalEntry | PaymentOrderJournalEntry | OrderCustomUpdatedJournalEntry;

/** General journal entry -- emitted for non-order actions */
export interface GeneralJournalEntry extends JournalEntry {
  journal: 'general';
  /** Entity type */
  type: 'product' | 'coupon' | 'config';
  /** Identifier of the entity that was changed */
  entityId: string;
  /** Who triggered the event */
  actor: string;
  /** Changed fields with before/after values */
  changes?: Record<string, unknown>;
  /** Full data payload (used when a changes map is not applicable) */
  data?: Record<string, unknown>;
}

// ─── Price rule types ─────────────────────────────────────────────────────────

export type ProductCondition = string | { path: string; sku?: string };

export interface VariantPriceRule {
  sku: string;
  price: string;
  start?: string;
  end?: string;
  metadata?: Record<string, string>;
}

export interface CatalogPriceRule {
  path: string;
  price: string;
  start?: string;
  end?: string;
  metadata?: Record<string, string>;
  /** Per-SKU overrides. Variants not listed inherit the parent product price. */
  variants?: Record<string, VariantPriceRule>;
}

export interface CatalogPromotion {
  id: string;
  name: string;
  rules: CatalogPriceRule[];
  country?: string;
  locale?: string;
  /** When present, the promotion is conditional and must not be applied during pipeline rendering.
   *  It is evaluated at cart/order estimate time against the current cart. */
  conditions?: CartPriceRuleConditions;
}

export interface CatalogPriceRules {
  promotions: CatalogPromotion[];
}

export interface CartPriceRuleConditions {
  minimumSubtotal?: number;
  requiredProducts?: ProductCondition[];
  excludedProducts?: ProductCondition[];
  requiredCategories?: string[];
  excludedCategories?: string[];
}

export interface CartPriceRuleActions {
  percentOff: number | null;
  fixedOff: number | null;
  freeShipping: boolean;
}

export interface CartPriceRule {
  id: string;
  name: string;
  priority: number;
  conditions: CartPriceRuleConditions;
  actions: CartPriceRuleActions;
  stackable: boolean;
  incompatibleTypes: string[];
}

/** Cart price rules -- array of auto-discount rules consumed by applyAutoRules */
export type CartPriceRules = CartPriceRule[];

/**
 * Configuration for order friendly ID generation.
 * The friendly ID is the short human-readable suffix appended to every orderId.
 */
export interface FriendlyIdConfig {
  /**
   * Character set for the friendly ID. Either a named preset or a literal string
   * where every character in the string is allowed.
   *
   * Named presets:
   *   "default" / omitted         - Crockford Base32 (0-9 A-Z minus I/L/O/U), uppercase
   *   "numeric"                   - 0-9
   *   "alphabetic"                - A-Z  (same as "alphabetic_uppercase")
   *   "alphabetic_uppercase"      - A-Z
   *   "alphabetic_lowercase"      - a-z
   *   "alphabetic_anycase"        - A-Za-z
   *   "alphanumeric"              - A-Z0-9  (same as "alphanumeric_uppercase")
   *   "alphanumeric_uppercase"    - A-Z0-9
   *   "alphanumeric_lowercase"    - a-z0-9
   *   "alphanumeric_anycase"      - A-Za-z0-9
   *
   * Literal charset: every character in the string is an allowed character.
   *   Must not contain "/".
   *   Must contain at least 2 distinct characters.
   */
  characters?: string;
  /**
   * Length of the friendly ID. Integer between 4 and 32 inclusive. Default: 8.
   */
  length?: number;
  /**
   * Literal string prepended to every generated friendly ID. Maximum 8 characters.
   * Same character restrictions as `characters` (no /?#&%<> or space).
   * Example: prefix "order" with characters "numeric" and length 10 produces "order1234567890".
   */
  prefix?: string;
}
